https://nightlies.apache.org/flink/flink-docs-master/docs/deployment/resource-providers/standalone/docker/


$ docker run \
    -itd \
    --rm \
    --name=jobmanager \
    --network flink-network \
    --publish 8081:8081 \
    --env FLINK_PROPERTIES="${FLINK_PROPERTIES}" \
    flink:latest jobmanager


$ docker run \
    -itd \
    --rm \
    --name=taskmanager \
    --network flink-network \
    --env FLINK_PROPERTIES="${FLINK_PROPERTIES}" \
    flink:latest taskmanager


$ ./bin/flink run ./examples/streaming/TopSpeedWindowing.jar